version: "3.6"

services:

  backend-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
      - 5000:80
      - 5001:433
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: src/Hestia.LocationsMDM.WebApi/Dockerfile
